### ISSUE TITLE
Seems to be incompatible with new Ruby versions

### ISSUE THREAD

**Issue by BenBlumer** [abhn/portfolio#29]
(disclaimer: I don't know Ruby at all.)

Trying to run it in the Jekyll Docker container:

```
$ docker run --rm   --volume="$PWD:/srv/jekyll:Z"   --publish [::1]:4000:4000   jekyll/jekyll   jekyll serve
Bundler 2.3.25 is running, but your lockfile was generated with 1.16.3. Installing Bundler 1.16.3 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 1.16.3
Installing bundler 1.16.3
Fetching gem metadata from https://rubygems.org/...........
ruby_dep-1.5.0 requires ruby version >= 2.2.5, ~> 2.2, which is incompatible
with the current version, ruby 3.1.1p18
```

**Comment by BenBlumer** [comment]
Similarly, trying an alternate Docker image:

```
$ export JEKYLL_VERSION=4.3.3
$ docker run --rm \
  --volume="$PWD:/srv/jekyll:Z" \
  -it jvconseil/jekyll-docker:$JEKYLL_VERSION \
  jekyll build
  
Status: Downloaded newer image for jvconseil/jekyll-docker:4.3.3
Bundler 2.5.5 is running, but your lockfile was generated with 1.16.3. Installing Bundler 1.16.3 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 1.16.3
Installing bundler 1.16.3
/usr/gem/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:266:in `search_up': undefined method `untaint' for an instance of String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:253:in `find_file'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:245:in `find_gemfile'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:27:in `root'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler.rb:219:in `root'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler.rb:229:in `app_config_path'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler.rb:258:in `settings'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/feature_flag.rb:21:in `block in settings_method'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/cli.rb:97:in `<class:CLI>'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/cli.rb:7:in `<module:Bundler>'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/cli.rb:6:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/gem/gems/bundler-1.16.3/exe/bundle:23:in `block in <top (required)>'
	from /usr/gem/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /usr/gem/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

**Comment by BenBlumer** [comment]
Fixed in PR #30
